apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-10-23T15:22:18Z"
  generation: 1
  labels:
    app: Docuseal
  name: Docuseal
  namespace: default
  resourceVersion: "79756"
  uid: 2b4e5432-3dcd-4003-8804-e10e1a288ded
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: Docuseal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: Docuseal
    spec:
      containers:
      - image: docuseal/docuseal:latest
        imagePullPolicy: Always
        name: docuseal
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
